defmodule Carbon.Repo.Migrations.AddForeignKeyIndexes do
  use Ecto.Migration

  def change do
    index :accounts, [ :billing_address_id ]
    index :accounts, [ :owner_id ]
    index :accounts, [ :shipping_address_id ]
    index :accounts, [ :status_id ]
    index :activities, [ :user_id ]
    index :attachments, [ :account_id ]
    index :attachments, [ :user_id ]
    index :contacts, [ :account_id ]
    index :deals, [ :account_id ]
    index :deals, [ :owner_id ]
    index :events, [ :account_id ]
    index :events, [ :user_id ]
    index :j_accounts_tags, [ :account_id ]
    index :j_accounts_tags, [ :account_tag_id ]
    index :j_contacts_tags, [ :contact_id ]
    index :j_contacts_tags, [ :contact_tag_id ]
    index :j_deals_tags, [ :deal_id ]
    index :j_deals_tags, [ :deal_tag_id ]
    index :j_events_tags, [ :event_id ]
    index :j_events_tags, [ :event_tag_id ]
    index :j_projects_tags, [ :project_id ]
    index :j_projects_tags, [ :project_tag_id ]
    index :j_timesheet_entries_tags, [ :timesheet_entry_id ]
    index :j_timesheet_entries_tags, [ :timesheet_entry_tag_id ]
    index :j_users_roles, [ :role_id ]
    index :j_users_roles, [ :user_id ]
    index :projects, [ :account_id ]
    index :projects, [ :phase_id ]
    index :reminders, [ :event_id ]
    index :reminders, [ :user_id ]
    index :rules, [ :user_id ]
    index :rules, [ :workflow_id ]
    index :timesheet_entries, [ :account_id ]
    index :timesheet_entries, [ :project_id ]
    index :timesheet_entries, [ :timesheet_id ]
    index :timesheets, [ :status_id ]
    index :timesheets, [ :user_id ]
    index :workflow_field_enums, [ :field_id ]
    index :workflow_field_values, [ :field_id ]
    index :workflow_field_values, [ :instance_id ]
    index :workflow_fields, [ :section_id ]
    index :workflow_instances, [ :state_id ]
    index :workflow_instances, [ :workflow_id ]
    index :workflow_sections, [ :workflow_id ]
    index :workflow_states, [ :workflow_id ]
  end
end
